### PR TITLE
Create VERSION

### PR DESCRIPTION
**Pull request by Nyx1197**
create a missing file

### CODE REVIEW

**Comment by Nyx1197** [comment]
it looks like missing a file, i test with myself project and it's works.

**Comment by adamu** [comment]
I think the problem is that [what was released](https://preview.hex.pm/preview/castore/0.1.21/show/mix.exs) (requires `VERSION`), is actually different to [what was tagged in GitHub](https://github.com/elixir-mint/castore/blob/v0.1.21/mix.exs) (does not require `VERSION`).

**Comment by Nyx1197** [comment]
i use `mix deps.get` update castore to 0.1.21, mix.exs look like this. 
https://github.com/elixir-mint/castore/issues/50#issue-1528360305

```elixir
  defp version do
    "VERSION"
    |> File.read!()
    |> String.trim()
  end
```

private function version require `VERSION`, and it's gone

**Comment by ericmj** [comment]
These changes `mix.exs` changes were not meant to be included. We have released 0.1.22 that matches what's on github.

**Comment by Nyx1197** [comment]
> These changes `mix.exs` changes were not meant to be included. We have released 0.1.22 that matches what's on github.

thanks

**Comment by whatyouhide** [comment]
Thanks for being on it folks!

**Pull request closed without merging**
