### PR TITLE
Remove expired certificates

### PR DESCRIPTION
**Pull request by jordi-chacon**
Remove two expired certificates from `priv/cacerts.pem`:
- The certificate from `Staat der Nederlanden Root CA - G2` expired on `Mar 25 11:03:10 2020 GMT`.
- The certificate from `AddTrust External Root` expired in `May 30 10:48:38 2020 GMT`.

### CODE REVIEW

**Comment by whatyouhide** [comment]
@jordi-chacon did you remove these manually or used `mix certdata`?

**Comment by jordi-chacon** [comment]
@whatyouhide I removed them manually because running `mix certdata` wouldn't get rid of the expired certificates. In fact, after I removed them manually I ran `mix certdata` and it added them back in the `cacerts.pem` file.

**Comment by whatyouhide** [comment]
@jordi-chacon then it seems like curl's certificates have not been updated yet?

**Comment by jordi-chacon** [comment]
@whatyouhide that's correct.

However, right after the `AddTrust External Root` certificate expired today, our production system started experiencing issues due to not being able to connect with a 3rd party API we are integrated with, causing major disturbances to our customers. This seems to be having more [widespread impact](https://chris.hofstaedtler.name/blog/2020/05/expired-root-failures.html).

We have already removed the expired certificates on our end through a fork, because waiting for curl's certificates to be updated was definitely not an option for us. I would guess the same is true for other people, thus the PR.

With that being said, you can definitely close this PR if you prefer to wait 👍

**Comment by whatyouhide** [comment]
FWIW, I think it might be easier to use your own certificate instead of forking castore. The point of castore is to provide a default _very trusted_ certificate store, used by one of the most widespread tools around (curl). We'll update when curl updates. In the meantime, it's going to be straightforward to use custom certificate store files directly 😊 

Thanks for the PR though!

**Pull request closed without merging**
