### PR TITLE
fix: skip update if check failed

### PR DESCRIPTION
**Pull request by vshev4enko**

### CODE REVIEW

**Comment by whatyouhide** [comment]
I might be out of it, but how does this differ from exiting with `1` and not updating in that case?

**Comment by vshev4enko** [comment]
outdated.sh returns 1 when e.g `curl` failed. this exit_code 2 (maybe not the best number for such purpose) intended to differentiate needs to update certs from any other script fail

**Comment by vshev4enko** [comment]
it does https://everything.curl.dev/cmdline/exitcode.html. There are e.g `20` marked as `Not used` and some up to 100. Not sure which one is better some from the gaps in the 1..99 range or some outside of range to avoid code occupation by future. I think we can use 100.

**Comment by whatyouhide** [comment]
Thanks @vshev4enko 💟

**Pull request merged**
