### PR TITLE
Except "AddTrust External Root" from store

### PR DESCRIPTION
**Pull request by ericmj**
The certificate is expired.

### CODE REVIEW

**Comment by voltone** [comment]
The regex wouldn't filter out a certificate if it were the last one in the file, with only a single newline, would it?

**Comment by ericmj** [comment]
> The regex wouldn't filter out a certificate if it were the last one in the file, with only a single newline, would it?

Correct, fixed now.

**Comment by voltone** [comment]
There's another expired certificate in there:
Staat der Nederlanden Root CA - G2

Do you want to maybe filter the result by expiry date in the Mix task? It might get a bit ugly without adding X509 as a dependency, but I can try...

**Comment by voltone** [comment]
No more expiring certs the rest of this year, but 5 more next year, including big ones like GlobalSign and DST. I imagine there'll be lots of cross-signed certificates out there that will not be accepted by Mint while the expired root lingers in CAStore...

**Comment by ericmj** [comment]
> Do you want to maybe filter the result by expiry date in the Mix task? It might get a bit ugly without adding X509 as a dependency, but I can try...

I don't know how to do that but something automated would be preferable because then we at least get notified by the nightly CI script and can push a new release quicker.

**Comment by ericmj** [comment]
> No more expiring certs the rest of this year, but 5 more next year, including big ones like GlobalSign and DST. I imagine there'll be lots of cross-signed certificates out there that will not be accepted by Mint while the expired root lingers in CAStore...

If there are 5 more next year then this doesn't really sound scalable, I feel like this needs to be fixed in the ssl application.

**Comment by voltone** [comment]
> I feel like this needs to be fixed in the ssl application

Yeah, I was hoping to meet Ingela at CodeBEAM SF to see whether the EEF Security WG could help push things forward. We've proposed some things in the past, but I thought it might get easier after a face-to-face meeting.

Anyway, I'll raise the issue on the Security WG mailing list, see what others have to say; there are some OTP team members on the list.

In the meantime, it wouldn't hurt to add a test that will fail if any certificates are set to expire in the next 48h or so: that would at least give you a heads-up. Even if the OTP team agree to improve the handling of alternate paths, it will be a while before that's rolled out to all Mint users.

**Comment by voltone** [comment]
I just created #18 to test for expired/expiring certificates. Feel free to use it or not, as you wish :)

**Pull request merged**
